<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="contrasena.png" />
    <None Remove="logo.png" />
    <None Remove="usuario.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="contrasena.png" />
    <Resource Include="logo.png" />
    <Resource Include="usuario.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modelos\" />
    <Folder Include="Docs\" />
    <Folder Include="Recursos\iconos\" />
    <Folder Include="VistaModelos\" />
    <Folder Include="Vistas\" />
  </ItemGroup>

</Project>
