<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="contrasena.png" />
    <None Remove="logo.png" />
    <None Remove="Recursos\iconos\contrasena.png" />
    <None Remove="Recursos\iconos\usuario.png" />
    <None Remove="Recursos\img\logo_1.png" />
    <None Remove="usuario.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="contrasena.png" />
    <Resource Include="logo.png" />
    <Resource Include="Recursos\iconos\contrasena.png" />
    <Resource Include="Recursos\iconos\usuario.png" />
    <Resource Include="Recursos\img\logo_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="usuario.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Docs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Vistas\MenuPrincipalOdontologia.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Vistas\Expedientes.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
